services:
  cassandra:
    image: cassandra:5.0.1
    container_name: cassandra
    environment:
      - CASSANDRA_AUTHENTICATOR=AllowAllAuthenticator
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 10s
      timeout: 5s
      retries: 5

  chroma:
    image: chromadb/chroma:0.5.23
    container_name: chroma
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:1.3.20
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
